
    create table analysis_runs (
        confidence float(53),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        action varchar(10),
        market varchar(10) not null,
        ticker varchar(40) not null,
        request_json text not null,
        response_json text not null,
        primary key (id)
    );

    create table api_usage_log (
        alpha_calls integer,
        cached boolean not null,
        days integer not null,
        http_status integer,
        news_limit integer not null,
        openai_calls integer,
        openai_tokens_in integer,
        openai_tokens_out integer,
        refresh boolean not null,
        test_mode boolean not null,
        web boolean not null,
        created_at timestamp(6) not null,
        duration_ms bigint,
        id bigint generated by default as identity,
        market varchar(8) not null,
        user_id bigint not null,
        endpoint varchar(32) not null,
        ticker varchar(32) not null,
        openai_model varchar(64),
        request_id varchar(64),
        error_text varchar(512),
        primary key (id)
    );

    create table backtest_runs (
        cagr float(53),
        max_drawdown float(53),
        sharpe float(53),
        total_return float(53),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        market varchar(10) not null,
        strategy varchar(30) not null,
        ticker varchar(40) not null,
        request_json text not null,
        response_json text not null,
        primary key (id)
    );

    create table backup_codes (
        used boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        used_at timestamp(6),
        user_id bigint not null,
        code_hash varchar(64) not null,
        primary key (id)
    );

    create table chat_conversations (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        model varchar(50),
        title varchar(200),
        context_json text,
        primary key (id)
    );

    create table chat_messages (
        tokens_in integer,
        tokens_out integer,
        conversation_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        role varchar(20) not null,
        model varchar(50),
        content text not null,
        primary key (id)
    );

    create table dividends (
        amount numeric(15,4) not null,
        currency varchar(3),
        declared_date date,
        ex_date date not null,
        payment_date date,
        record_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        portfolio_position_id bigint not null,
        frequency varchar(20),
        primary key (id)
    );

    create table market_cache (
        days integer not null,
        news_limit integer not null,
        test_mode boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        insights_updated_at timestamp(6),
        market varchar(8) not null,
        report_updated_at timestamp(6),
        user_id bigint not null,
        ticker varchar(32) not null,
        insights_json text,
        report_text text,
        primary key (id),
        constraint uk_market_cache_key unique (user_id, ticker, market, test_mode, days, news_limit)
    );

    create table market_report_history (
        cache_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        report_text text not null,
        primary key (id)
    );

    create table paper_accounts (
        balance numeric(20,4) not null,
        currency varchar(4) not null,
        initial_balance numeric(20,4) not null,
        market varchar(4) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        primary key (id)
    );

    create table paper_orders (
        amount numeric(20,4) not null,
        commission numeric(20,4) not null,
        direction varchar(4) not null,
        price numeric(15,4) not null,
        quantity numeric(15,4) not null,
        account_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        ticker varchar(32) not null,
        primary key (id)
    );

    create table paper_positions (
        avg_price numeric(15,4) not null,
        quantity numeric(15,4) not null,
        total_cost numeric(20,4) not null,
        account_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        ticker varchar(32) not null,
        primary key (id)
    );

    create table portfolio_positions (
        entry_date date,
        entry_price numeric(15,4) not null,
        quantity numeric(15,4) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        market varchar(8) not null,
        portfolio_id bigint not null,
        updated_at timestamp(6),
        ticker varchar(32) not null,
        notes varchar(500),
        primary key (id)
    );

    create table portfolios (
        target_return numeric(5,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        risk_profile varchar(20),
        name varchar(100) not null,
        description varchar(500),
        primary key (id)
    );

    create table price_alerts (
        enabled boolean not null,
        notification_sent boolean,
        threshold numeric(15,4) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        market varchar(8) not null,
        triggered_at timestamp(6),
        user_id bigint not null,
        alert_type varchar(20) not null,
        ticker varchar(32) not null,
        primary key (id)
    );

    create table refresh_tokens (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_used_at timestamp(6),
        user_id bigint not null,
        token_hash varchar(64) not null unique,
        token varchar(512) not null unique,
        primary key (id)
    );

    create table screener_presets (
        is_public boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        name varchar(100) not null,
        description varchar(500),
        filters_json text not null,
        primary key (id)
    );

    create table totp_secrets (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        verified_at timestamp(6),
        secret varchar(32) not null,
        primary key (id)
    );

    create table user_settings (
        daily_summary_enabled boolean not null,
        email_on_alerts boolean not null,
        totp_enabled boolean not null,
        created_at timestamp(6) not null,
        default_market varchar(8),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null unique,
        language varchar(10),
        theme varchar(20),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        role varchar(30) not null,
        password_hash varchar(100) not null,
        email varchar(190) not null,
        primary key (id),
        constraint uk_users_email unique (email)
    );

    create table watchlist (
        test_mode boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        market varchar(8) not null,
        user_id bigint not null,
        ticker varchar(32) not null,
        notes varchar(500),
        primary key (id),
        constraint uk_watchlist unique (user_id, ticker, market, test_mode)
    );

    create table watchlist_item_tag (
        tag_id bigint not null,
        watchlist_item_id bigint not null,
        primary key (tag_id, watchlist_item_id)
    );

    create table watchlist_tag (
        color varchar(7),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        name varchar(50) not null,
        primary key (id),
        constraint uk_watchlist_tag unique (user_id, name)
    );

    create index idx_analysis_runs_user_created 
       on analysis_runs (user_id, created_at);

    create index idx_usage_user_created 
       on api_usage_log (user_id, created_at);

    create index idx_usage_request_id 
       on api_usage_log (request_id);

    create index idx_backtest_runs_user_created 
       on backtest_runs (user_id, created_at);

    create index idx_hist_cache_created 
       on market_report_history (cache_id, created_at);

    alter table if exists analysis_runs 
       add constraint FKgvfcg4aw75wblrl4akr70j2tg 
       foreign key (user_id) 
       references users;

    alter table if exists api_usage_log 
       add constraint FK1orsbiex6artorme20ufihtoh 
       foreign key (user_id) 
       references users;

    alter table if exists backtest_runs 
       add constraint FKsfepb9la3evn5kk3ujhrwqx1e 
       foreign key (user_id) 
       references users;

    alter table if exists backup_codes 
       add constraint FK4uqupj7j6eldpff5ycw8vnpm6 
       foreign key (user_id) 
       references users;

    alter table if exists chat_conversations 
       add constraint FK40okueacd48n616c3r1nvjwpr 
       foreign key (user_id) 
       references users;

    alter table if exists chat_messages 
       add constraint FKqgkanrr90j46564w4ww63jcna 
       foreign key (conversation_id) 
       references chat_conversations;

    alter table if exists dividends 
       add constraint FKnw4gk7p1lrmtyjtdrp3xcsu4l 
       foreign key (portfolio_position_id) 
       references portfolio_positions;

    alter table if exists market_cache 
       add constraint FKq6og16opmk5h9koe30qtfvy4t 
       foreign key (user_id) 
       references users;

    alter table if exists market_report_history 
       add constraint FKt4hgcjugv3hsmh4jef71qsg40 
       foreign key (cache_id) 
       references market_cache;

    alter table if exists paper_accounts 
       add constraint FKiy4nnccf233nmajgol19yjya2 
       foreign key (user_id) 
       references users;

    alter table if exists paper_orders 
       add constraint FKio4m0igac9bj7xetg4eom2e17 
       foreign key (account_id) 
       references paper_accounts;

    alter table if exists paper_positions 
       add constraint FKqeyta09uvi4cufgaqxptkgsrk 
       foreign key (account_id) 
       references paper_accounts;

    alter table if exists portfolio_positions 
       add constraint FKjaiaieo24ssj1ulgnp7bowc46 
       foreign key (portfolio_id) 
       references portfolios;

    alter table if exists portfolios 
       add constraint FK9xt36kgm9cxsf79r2me0d9f6u 
       foreign key (user_id) 
       references users;

    alter table if exists price_alerts 
       add constraint FKaqq01qkath6ujf2ikwey10q8l 
       foreign key (user_id) 
       references users;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists screener_presets 
       add constraint FKgqvfv09rm6mab0slafm1yvckc 
       foreign key (user_id) 
       references users;

    alter table if exists totp_secrets 
       add constraint FK3y28un1iib4airw82n94j8jxk 
       foreign key (user_id) 
       references users;

    alter table if exists user_settings 
       add constraint FK8v82nj88rmai0nyck19f873dw 
       foreign key (user_id) 
       references users;

    alter table if exists watchlist 
       add constraint FKden7i83qo2swnr5br4wgc5r7j 
       foreign key (user_id) 
       references users;

    alter table if exists watchlist_item_tag 
       add constraint FKkl6a14809jyr362efr0n52ct6 
       foreign key (tag_id) 
       references watchlist_tag;

    alter table if exists watchlist_item_tag 
       add constraint FKq96mffjb7nrlollb3gffmdfto 
       foreign key (watchlist_item_id) 
       references watchlist;

    alter table if exists watchlist_tag 
       add constraint FK4l3v6lfj2ae1g6wt2shxf1ne5 
       foreign key (user_id) 
       references users;
